# Generated by Django 3.2.5 on 2021-08-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Date_hired',
            new_name='date_hired',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Languages',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='National_id',
            new_name='national_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Nationality',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
