# Generated by Django 3.2.5 on 2021-08-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210819_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='profile',
            new_name='image',
        ),
    ]
