# Generated by Django 3.2.5 on 2021-08-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=20)),
                ('Course_code', models.SmallIntegerField()),
                ('Syllabus', models.CharField(max_length=50)),
                ('Course_shedule', models.DateTimeField()),
                ('Course_duration', models.DurationField()),
                ('Course_Instractor', models.CharField(max_length=25)),
            ],
        ),
    ]
