# Generated by Django 3.2.5 on 2021-08-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(choices=[('Uganda', 'Uganda'), ('Kenya', 'Kenya'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('South', 'Sudan')], default='Uganda', max_length=20)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=7)),
                ('student_Id', models.PositiveSmallIntegerField()),
                ('nationality', models.CharField(max_length=20)),
                ('national_Id', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=20)),
                ('role_number', models.CharField(max_length=4)),
                ('date_of_enrolment', models.DateField()),
                ('medical_report', models.FileField(upload_to='')),
                ('laptop_number', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=14)),
            ],
        ),
    ]
