# Generated by Django 3.2.5 on 2021-08-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_enrolment',
            field=models.DateField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(blank='True', max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='laptop_number',
            field=models.CharField(blank='True', max_length=5, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(blank='True', null='True', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_Id',
            field=models.CharField(blank='True', max_length=25, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank='True', max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank='True', max_length=15, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='role_number',
            field=models.CharField(blank='True', max_length=4, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Id',
            field=models.PositiveSmallIntegerField(blank='True', null='True'),
        ),
    ]
