# Generated by Django 3.2.5 on 2021-08-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210815_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile',
            new_name='image',
        ),
    ]
